CREATE TABLE JAATM_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JUID VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,

    CONSTRAINT UK_JAAT_USER_JUID UNIQUE (JUID)
);

CREATE TABLE JAATM_ACCOUNT (
    ID BIGINT  AUTO_INCREMENT PRIMARY KEY,
    BALANCE VARCHAR(50),
    STATUS VARCHAR(20),
    JAATM_USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_ACCOUNT_USER
        FOREIGN KEY (JAATM_USER_ID)
        REFERENCES JAATM_USER(ID)
        ON DELETE CASCADE
);

CREATE TABLE JAATM_ADDRESS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STREET_NUMBER VARCHAR(20),
    STREET_NAME VARCHAR(150),
    TOWN VARCHAR(100),
    CITY VARCHAR(100),
    PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    JAATM_USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_ADDRESS_USER_1
        FOREIGN KEY (JAATM_USER_ID)
        REFERENCES JAATM_USER(ID)
        ON DELETE CASCADE
);


