CREATE TABLE JAAT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JUID VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,

    CONSTRAINT UK_JAAT_USER_JUID UNIQUE (JUID)
);
