/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.ashtech.jaatm.bea.controller;

import java.util.Optional;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.context.request.NativeWebRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import za.co.ashtech.jaatm.bea.dto.GetAccountResponse;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-26T15:33:20.126202100+02:00[Africa/Johannesburg]")
@Validated
@Tag(name = "account", description = "Everything about your Pets")
public interface AccountApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /account/{juid} : Get account details for a given juid
     * This API provides retrieval of the current account balance associated with a specified JUID.
     *
     * @param juid  (required)
     * @return Successful response (status code 200)
     */
    @Operation(
        operationId = "GetAccountBalance",
        summary = "Get account details for a given juid",
        description = "This API provides retrieval of the current account balance associated with a specified JUID.",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetAccountResponse.class))
            })
        }
    )
    @GetMapping(
        value = "/account/{juid}",
        produces = { "application/json" }
    )
    
    ResponseEntity<GetAccountResponse> getAccountBalance(@Parameter(name = "juid", description = "", required = true, in = ParameterIn.PATH) @PathVariable("juid") String juid);
}
